services:
    app:
        container_name: gravitylabs_app
        restart: unless-stopped
        tty: true
        build:
            context: ./config
            dockerfile: ./_docker/Dockerfile
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./storage/logs/laravel:/var/log/laravel
        depends_on:
            - database
        networks:
            - app-network

    webserver:
        image: nginx:stable-alpine
        container_name: gravitylabs_webserver
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - ./config/_docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - app-network

    database:
        image: postgres:15
        container_name: gravitylabs_dbserver
        restart: unless-stopped
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: gravitylabs
        ports:
            - "5432:5432"
        volumes:
            - ./config/_docker/dbdata:/var/lib/postgresql/data
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
